spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:/data/demo
#    url: jdbc:h2:C:/data/demo  
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: obus
    timeout: 60000
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
          
server:
  port: 9991
  servlet:
    session:
      timeout: 3600s
#  context:
#    path: /api
    
app:
  user:
    username: admin
    password: password
  oauth:
    client-id: obus-client
    client-secret: obus-secret
    redirect-urls: http://localhost:9991/login
    access-token-validity: 3600
    refresh-token-validity: 21600

#security:
#  oauth2:
#    resource:
#      filter-order: 3