DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
	ID UUID DEFAULT random_uuid() PRIMARY KEY,
	USERNAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	FULLNAME VARCHAR(255) NOT NULL
);
